SELECT /*+index(A IDX_AC_FECHA_CNTA_CTRL_02) */
       B.COD_CLIE, B.NOM_CLIE CLIENTE,
       DECODE(B.IND_ACTI,1,'ACTIVO','INACTIVO') ESTADO,
       A.FEC_PROC_APER FECHA,
       A.COD_CNTA CUENTA,
       A.COD_BOVE BOVEDA,
       A.EST_SALD
FROM   VE_CLIENTE B, AC_FECHA_CNTA_CTRL A
WHERE  A.FEC_PROC_APER < TO_DATE('31/01/2017','DD/MM/YYYY')--SYSDATE - 1
AND  A.COD_CLIE=B.COD_CLIE
AND    A.COD_SUCU_HTB = 2
AND    B.IND_ACTI=1
AND    A.EST_SALD='1'
ORDER BY A.COD_CLIE,A.FEC_PROC_APER,CUENTA,BOVEDA;

Select q.* From AC_FECHA_CNTA_CTRL q where q.cod_clie=14 and q.cod_cnta=2 and q.cod_bove=1 and q.est_sald='1' for update;
