SELECT A.COD_CLIE_CNTA CODCLIE,
       INITCAP(C.NOM_CLIE) NOMCLIE,
       A.COD_CNTA CODCNTA,
       (SELECT X.DES_CNTA
          FROM AC_CUENTA X
         WHERE X.COD_SUCU_HTB = A.COD_SUCU_HTB_CNTA
           AND X.COD_CLIE = A.COD_CLIE_CNTA
           AND X.COD_CNTA = A.COD_CNTA) DESCNTA,
       A.TIP_DOCU_CMPB TIPDOCUCMPB,
       A.COD_SERI_CMPB CODSERICMPB,
       A.NUM_CMPB NUMCMPB,
       A.TIP_PUNT_ORIG TIPOCS,
       (SELECT X.DES_TIPO
          FROM TG_TABL_TIPO X
         WHERE X.COD_GRUP_TIPO = 624
           AND X.COD_TIPO = A.TIP_ORIG) DESTIPOCS,
       A.TIP_ORIG TIPORIG,
       (SELECT DES_TIPO
          FROM TG_TABL_TIPO
         WHERE COD_GRUP_TIPO = '2'
           AND COD_TIPO = A.TIP_PUNT_ORIG
           AND IND_ACTI = '1') DESTIPORIG,
       NVL(B.COD_EQUI_AGEN, B.COD_PUNT) CODPUNTORIG,
       K.COD_EQUI_AGEN CODMATRIZ,
       NVL(NVL(K.DES_EQUI_AGEN, K.DES_PUNT), 'Puntos sin matriz asignada') DESMATRIZ,
       E.TIP_UNID_MONE TIPUNIDMONE,
       E.TIP_MONE TIPMONE,
       INITCAP(NVL(B.DES_EQUI_AGEN, B.DES_PUNT)) DESPUNTORIG,
       '' CODPUNTDEST,
       INITCAP(B.DES_EQUI_AGEN) DESBANCPUNTORIG,
       '' DESBANCPUNTDEST,
       INITCAP(B.DES_PUNT) DESHTBPUNTORIG,
       '' DESHTBPUNTDEST,
       K.DES_EQUI_AGEN DESBANCMATRIZ,
       K.DES_PUNT DESHTBMATRIZ,
       TO_CHAR(G.FEC_PROC_APER, 'dd/mm/yyyy') FECPROCAPER,
       I.DES_TIPO DESTIPUNIDMONE,
       H.DES_TIPO DESTIPMONE,
       E.COD_DENO CODDENO,
       E.COD_BOVE CODBOVE,
       (SELECT DES_BOVE
          FROM AC_BOVEDA X
         WHERE X.COD_SUCU_HTB = A.COD_SUCU_HTB_CNTA
           AND X.COD_BOVE = E.COD_BOVE) DESBOVE,
       F.CAN_VALO_NOMI CANVALONOMI,
       E.MON_DENO MONDENO,
       E.CAN_PIEZ PIEZAS,
       NVL(SHAC.SHPG_BILL_RECO.SHFU_CONV_LADR(F.TIP_UNID_MONE,
                                              F.COD_DENO,
                                              E.TIP_MONE,
                                              E.CAN_PIEZ,
                                              1),
           '0') LADRILLOS
  FROM TV_CMPB_SERV        A,
       AC_CMPB_DENO        E,
       TVTD_MONT_CMPB_BOVE G,
       VE_PUNTO            B,
       VE_CLIENTE          C,
       TG_TABL_TIPO        H,
       AC_DENO_MONE        F,
       TG_TABL_TIPO        I,
       VE_CLIE_PUNT        J,
       VE_PUNTO            K
 WHERE 
       A.NUM_CMPB = E.NUM_CMPB
   AND A.COD_SERI_CMPB = E.COD_SERI_CMPB
   AND A.TIP_DOCU_CMPB = E.TIP_DOCU_CMPB
   AND A.NUM_CMPB = G.NUM_CMPB
   AND A.COD_SERI_CMPB = G.COD_SERI_CMPB
   AND A.TIP_DOCU_CMPB = G.TIP_DOCU_CMPB
   AND E.NUM_CMPB = G.NUM_CMPB
   AND E.COD_SERI_CMPB = G.COD_SERI_CMPB
   AND E.TIP_DOCU_CMPB = G.TIP_DOCU_CMPB
   AND E.COD_BOVE = G.COD_BOVE
   AND A.COD_PUNT_ORIG = B.COD_PUNT
   AND A.COD_CLIE_CNTA = C.COD_CLIE
/*   AND (:B18 = '0' OR
       E.COD_DENO IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B18))))*/
   AND A.TIP_DEST = '3'
   AND A.TIP_FORM_TRAS = '2'
   AND A.EST_RECU NOT IN ('0', '1')
   AND A.EST_DOCU <> '11'
   AND H.COD_GRUP_TIPO = 20
   AND H.COD_TIPO = E.TIP_MONE
   AND I.COD_GRUP_TIPO = 19
   AND I.COD_TIPO = E.TIP_UNID_MONE
   AND F.TIP_PROD = E.TIP_PROD
   AND F.TIP_UNID_MONE = E.TIP_UNID_MONE
   AND F.TIP_MONE = E.TIP_MONE
   AND F.COD_DENO = E.COD_DENO
   AND J.COD_PUNT(+) = A.COD_PUNT_ORIG
   AND K.COD_PUNT(+) = J.COD_PUNT_SUCU_CLIE
   AND J.COD_CLIE(+) = A.COD_CLIE_CNTA
  /* AND ((:B17 = '0') OR
       (J.COD_PUNT_SUCU_CLIE IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B17)))))
   AND (:B16 = '0' OR
       A.COD_PUNT_ORIG IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B16))))
   AND ((:B15 = '0') OR (:B15 = '1' AND A.TIP_PUNT_ORIG IN (1, 4, 12)) OR
       (A.TIP_PUNT_ORIG IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B15)))))
   AND (:B14 = '0' OR
       A.COD_SUCU_HTB_CNTA IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B14))))*/
   AND 
       (A.FEC_PROC >= TO_DATE('01/01/2016', 'dd/mm/yyyy') AND
       A.FEC_PROC <= TO_DATE('31/12/2016', 'dd/mm/yyyy'))
       
       AND B.COD_CLIE_GRUP IN  (2947,340,3251)
 /*      
   AND ((:B8 = 2 AND
       (:B7 = '0' OR
       A.COD_CLIE_CNTA IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B7))))) OR
       (:B8 = 3 AND
       (:B7 = '0' OR
       B.COD_CLIE_GRUP  IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B7))))))*/
       /*
   AND ((:B6 IS NULL) OR
       ((:B6 = '0' AND
       A.COD_CLIE_CNTA NOT IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B7)))) OR
       A.COD_CLIE_CNTA IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B6)))))
   AND ((:B5 IS NULL) OR
       (:B5 = '0' OR
       A.COD_CNTA || '-' || A.COD_SUCU_HTB_CNTA || '-' || A.COD_CLIE_CNTA IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B5)))))
   AND (:B4 IS NULL OR
       (:B4 = '0' OR
       A.COD_SUCU_HTB_CNTA || '-' || G.COD_BOVE IN
       (SELECT * FROM TABLE(APERTURA.HWPG_TABL.HWFU_RETU_IN_LIST(:B4)))))
   AND (:B3 IS NULL OR (:B3 = '0' OR :B3 = E.TIP_UNID_MONE))
   AND ((:B2 = '0') OR (A.TIP_ORIG = :B1))*/
   and A.COD_CLIE_CNTA in (224,15)
 ORDER BY G.FEC_PROC_APER, B.DES_PUNT, A.COD_SERI_CMPB, A.NUM_CMPB
