Select *
  From TRASLADO.TV_CMPB_SERV
 WHERE TIP_DOCU_CMPB = 'CS'
   AND COD_SERI_CMPB = 'B03'
   AND NUM_CMPB = 138152;
   
   Select * From TRASLADO.TV_CMPB_ENVASE
   WHERE TIP_DOCU_CMPB = 'CS'
   AND COD_SERI_CMPB = 'B03'
   AND NUM_CMPB = 138152;
